import type {CollectionKey, CollectionState, FilterState, OutboxItem, PageKey} from './types'
import {expiringContracts} from './domain'

export const REAL_RETAIL_SANDBOX_ID = 'sandbox-customer-real-retail-20260425'
export const DEFAULT_PLATFORM_ID = 'platform-longfor-paradise-walk'
export const DEFAULT_PROJECT_ID = 'project-chengdu-binjiang-paradise-walk'
export const DEFAULT_STORE_ID = 'store-cd-binjiang-butterful'
export const DEFAULT_BRAND_ID = 'brand-longfor-butterful'
export const DEFAULT_TABLE_PAGE_SIZE = 12
export const TABLE_PAGE_SIZE_OPTIONS = [10, 12, 20, 50]

export const emptyCollections: CollectionState = {
  sandboxes: [],
  platforms: [],
  projects: [],
  tenants: [],
  brands: [],
  contracts: [],
  businessEntities: [],
  stores: [],
  tables: [],
  workstations: [],
  permissions: [],
  roles: [],
  users: [],
  roleBindings: [],
  products: [],
  productCategories: [],
  brandMenus: [],
  storeMenus: [],
  storeConfig: [],
  stock: [],
  availability: [],
  priceRules: [],
  availabilityRules: [],
}

export const emptyFilter: FilterState = {
  search: '',
  status: 'ALL',
  platformId: 'ALL',
  projectId: 'ALL',
  storeId: 'ALL',
  brandId: 'ALL',
  tenantId: 'ALL',
  roleId: 'ALL',
  category: 'ALL',
  floor: 'ALL',
  contractStatus: 'ALL',
  operatingStatus: 'ALL',
  erpStatus: 'ALL',
  standardMenu: 'ALL',
  activeContract: 'ALL',
  storeType: 'ALL',
  productType: 'ALL',
  priceType: 'ALL',
  channelType: 'ALL',
  region: 'ALL',
  businessMode: 'ALL',
  billingMode: 'ALL',
  permissionType: 'ALL',
  roleType: 'ALL',
  scopeType: 'ALL',
  policyEffect: 'ALL',
  ownershipScope: 'ALL',
  reviewStatus: 'ALL',
  tableStatus: 'ALL',
  capacity: 'ALL',
  workstationCategory: 'ALL',
  workstationType: 'ALL',
  tableArea: 'ALL',
  tableType: 'ALL',
  reservable: 'ALL',
  availabilityState: 'ALL',
  availabilityRuleType: 'ALL',
  businessStatus: 'ALL',
  productId: 'ALL',
  productCategoryId: 'ALL',
  stockLevel: 'ALL',
  discountType: 'ALL',
  settlementCycle: 'ALL',
  sandboxType: 'ALL',
  isvStatus: 'ALL',
  userId: 'ALL',
  permissionId: 'ALL',
}

export const navGroups: Array<{title: string; pages: Array<{key: PageKey; label: string; badge?: (data: CollectionState, outbox: OutboxItem[]) => number}>}> = [
  {title: '工作台', pages: [{key: 'dashboard', label: '待处理事项'}, {key: 'dataStatistics', label: '数据统计'}]},
  {title: '环境管理', pages: [{key: 'environment', label: '沙箱'}]},
  {
    title: '组织管理',
    pages: [
      {key: 'platforms', label: '平台'},
      {key: 'businessDictionaries', label: '业务字典'},
      {key: 'projects', label: '项目'},
      {key: 'tenants', label: '租户'},
      {key: 'brands', label: '品牌'},
      {key: 'stores', label: '门店'},
      {key: 'contracts', label: '经营合同', badge: data => expiringContracts(data.contracts).length},
    ],
  },
  {title: '设施管理', pages: [{key: 'tables', label: '桌台'}, {key: 'workstations', label: '工作站'}]},
  {
    title: 'IAM',
    pages: [
      {key: 'permissions', label: '权限'},
      {key: 'roles', label: '角色'},
      {key: 'users', label: '用户'},
      {key: 'roleBindings', label: '角色绑定'},
    ],
  },
  {title: '商品中心', pages: [{key: 'productCategories', label: '商品分类'}, {key: 'products', label: '商品库'}, {key: 'brandMenus', label: '品牌菜单'}]},
  {title: '菜单中心', pages: [{key: 'storeMenus', label: '门店菜单'}]},
  {
    title: '经营配置',
    pages: [
      {key: 'storeConfig', label: '营业配置'},
      {key: 'stock', label: '可售库存'},
      {key: 'availabilityRules', label: '可售规则'},
      {key: 'availability', label: '可售状态'},
      {key: 'priceRules', label: '价格规则'},
    ],
  },
  {title: '投影监控', pages: [{key: 'projectionOutbox', label: '投影队列', badge: (_data, outbox) => outbox.filter(item => item.status === 'FAILED').length}, {key: 'publishLog', label: '发布日志'}]},
]

export const pageMeta: Record<PageKey, {title: string; scope: string; collection?: CollectionKey; createLabel?: string; emptyAction?: string}> = {
  dashboard: {title: '工作台', scope: '今天需要处理的主数据和投影事项'},
  dataStatistics: {title: '数据统计', scope: '当前沙箱和平台下的主数据规模、健康度和投影风险'},
  environment: {title: '沙箱环境', scope: '沙箱是业务数据的顶层隔离单元', collection: 'sandboxes', createLabel: '新建沙箱'},
  platforms: {title: '平台管理', scope: '当前沙箱下的商业集团平台', collection: 'platforms', createLabel: '新建平台'},
  businessDictionaries: {title: '集团业务字典', scope: '当前平台下统一维护的大区、业态和业务选项'},
  projects: {title: '项目管理', scope: '当前平台下的商业项目', collection: 'projects', createLabel: '新建项目'},
  tenants: {title: '租户管理', scope: '当前平台下的签约租户', collection: 'tenants', createLabel: '新建租户'},
  brands: {title: '品牌管理', scope: '品牌直属平台，通过合同关联到门店', collection: 'brands', createLabel: '新建品牌'},
  businessEntities: {title: '签约/结算主体', scope: '租户详情和合同签署使用的法人主体资料，不作为一级业务菜单', collection: 'businessEntities', createLabel: '新增主体'},
  contracts: {title: '经营合同', scope: '合同决定门店当前租户和品牌', collection: 'contracts', createLabel: '新建合同'},
  stores: {title: '门店管理', scope: '当前平台下的铺位、经营状态和合同健康', collection: 'stores', createLabel: '新建门店'},
  tables: {title: '桌台管理', scope: '当前平台下各门店的堂食桌台配置', collection: 'tables', createLabel: '新建桌台'},
  workstations: {title: '工作站管理', scope: '当前平台下各门店的制作工作站配置', collection: 'workstations', createLabel: '新建工作站'},
  permissions: {title: '权限管理', scope: '当前平台下的系统和自定义权限', collection: 'permissions', createLabel: '新建权限'},
  roles: {title: '角色管理', scope: '当前平台下角色、权限和授权用户', collection: 'roles', createLabel: '新建角色'},
  users: {title: '用户管理', scope: '门店和平台人员账号', collection: 'users', createLabel: '新建用户'},
  roleBindings: {title: '角色绑定', scope: '用户-角色-授权范围审计视图', collection: 'roleBindings', createLabel: '授予角色'},
  productCategories: {title: '商品分类', scope: '品牌或门店商品分类，供商品、菜单和统计使用', collection: 'productCategories', createLabel: '新建商品分类'},
  products: {title: '商品库', scope: '当前平台下品牌商品、规格、加料和制作配置', collection: 'products', createLabel: '新建商品'},
  brandMenus: {title: '品牌菜单', scope: '品牌标准菜单、分区和商品关系', collection: 'brandMenus', createLabel: '新建品牌菜单'},
  storeMenus: {title: '门店菜单', scope: '门店实际生效菜单、价格覆盖和可售规则', collection: 'storeMenus', createLabel: '新建门店菜单'},
  storeConfig: {title: '营业参数', scope: '当前平台下各门店渠道入口、营业时段和附加费等交易前置配置，不执行订单或履约动作', collection: 'storeConfig', createLabel: '维护参数'},
  stock: {title: '可售库存', scope: '当前平台下各门店商品可售口径、下游占用汇总和预警', collection: 'stock', createLabel: '维护库存'},
  availabilityRules: {title: '可售规则', scope: '当前平台下各门店商品按渠道、时段、库存和限量的可售规则', collection: 'availabilityRules', createLabel: '新建可售规则'},
  availability: {title: '商品可售状态', scope: '当前平台下各门店商品即时可售状态', collection: 'availability', createLabel: '修改可售状态'},
  priceRules: {title: '价格规则', scope: '当前平台下各门店渠道、时段和会员价格规则', collection: 'priceRules', createLabel: '新建价格规则'},
  projectionOutbox: {title: '投影队列', scope: '写操作进入终端投影的处理状态'},
  publishLog: {title: '发布日志', scope: '投影发布到终端平台的请求和结果'},
}

export const pageToEntityType: Partial<Record<PageKey, string>> = {
  platforms: 'platform',
  projects: 'project',
  tenants: 'tenant',
  brands: 'brand',
  businessEntities: 'business_entity',
  contracts: 'contract',
  stores: 'store',
  tables: 'table',
  workstations: 'workstation',
  permissions: 'permission',
  roles: 'role',
  users: 'user',
  roleBindings: 'user_role_binding',
  productCategories: 'product_category',
  products: 'product',
  brandMenus: 'brand_menu',
  storeMenus: 'menu_catalog',
  storeConfig: 'store_config',
  stock: 'saleable_stock',
  availabilityRules: 'availability_rule',
  availability: 'menu_availability',
  priceRules: 'price_rule',
}

const editablePages = new Set<PageKey>([
  'platforms',
  'projects',
  'tenants',
  'brands',
  'businessEntities',
  'contracts',
  'stores',
  'tables',
  'workstations',
  'permissions',
  'roles',
  'users',
  'productCategories',
  'products',
  'brandMenus',
  'storeMenus',
  'storeConfig',
  'stock',
  'availabilityRules',
  'availability',
  'priceRules',
])

export const canEditPage = (page: PageKey) => editablePages.has(page)
