import type {
  ActivationCodeItem,
  ActivationResult,
  ApiResponse,
  AuditLogItem,
  BrandItem,
  ChangeLogItem,
  FaultRuleItem,
  ImportValidationResult,
  OverviewStats,
  PaginatedResult,
  ProfileItem,
  ProjectionItem,
  ProjectItem,
  SandboxItem,
  SceneTemplateItem,
  ScopeStats,
  SessionItem,
  StoreItem,
  TaskInstanceItem,
  TaskReleaseItem,
  TaskTrace,
  TenantItem,
  TenantBrandAuthorizationItem,
  TemplateLibraryItem,
  TerminalItem,
  TerminalTemplateItem,
  TopicItem,
  RuntimeContext,
} from './types'

async function request<T>(url: string, options?: RequestInit): Promise<T> {
  const response = await fetch(url, {
    headers: {
      'Content-Type': 'application/json',
      ...(options?.headers ?? {}),
    },
    ...options,
  })

  const payload = (await response.json()) as ApiResponse<T>
  if (!response.ok || !payload.success) {
    throw new Error(payload.error?.message ?? `Request failed: ${response.status}`)
  }

  return payload.data
}

export const api = {
  getOverview: () => request<OverviewStats>('/api/v1/admin/overview'),
  getRuntimeContext: () => request<RuntimeContext>('/api/v1/admin/runtime-context'),
  switchCurrentSandbox: (sandboxId: string) => request<RuntimeContext>('/api/v1/admin/runtime-context/current-sandbox', { method: 'PUT', body: JSON.stringify({ sandboxId }) }),
  getSandboxes: () => request<SandboxItem[]>('/api/v1/admin/sandboxes'),
  createSandbox: (payload: Record<string, unknown>) => request<SandboxItem>('/api/v1/admin/sandboxes', { method: 'POST', body: JSON.stringify(payload) }),
  updateSandbox: (sandboxId: string, payload: Record<string, unknown>) => request<SandboxItem>(`/api/v1/admin/sandboxes/${sandboxId}`, { method: 'PUT', body: JSON.stringify(payload) }),
  getAuditLogs: (page = 1, pageSize = 10) => request<PaginatedResult<AuditLogItem>>(`/api/v1/admin/audit-logs?page=${page}&pageSize=${pageSize}`),
  exportAll: () => request<Record<string, unknown>>('/api/v1/admin/export'),
  getTopicLibrary: () => request<TemplateLibraryItem[]>('/api/v1/admin/templates/topic-library'),
  getFaultLibrary: () => request<TemplateLibraryItem[]>('/api/v1/admin/templates/fault-library'),
  validateImportTemplates: (payload: Record<string, unknown>) => request<ImportValidationResult>('/api/v1/admin/import/templates/validate', { method: 'POST', body: JSON.stringify(payload) }),
  importTemplates: (payload: Record<string, unknown>) => request('/api/v1/admin/import/templates', { method: 'POST', body: JSON.stringify(payload) }),
  getTenants: () => request<TenantItem[]>('/api/v1/admin/master-data/tenants'),
  createTenant: (payload: Record<string, unknown>) => request('/api/v1/admin/master-data/tenants', { method: 'POST', body: JSON.stringify(payload) }),
  updateTenant: (tenantId: string, payload: Record<string, unknown>) => request(`/api/v1/admin/master-data/tenants/${tenantId}`, { method: 'PUT', body: JSON.stringify(payload) }),
  getBrands: () => request<BrandItem[]>('/api/v1/admin/master-data/brands'),
  getTenantBrandAuthorizations: () => request<TenantBrandAuthorizationItem[]>('/api/v1/admin/master-data/tenant-brand-authorizations'),
  createTenantBrandAuthorization: (payload: Record<string, unknown>) => request('/api/v1/admin/master-data/tenant-brand-authorizations', { method: 'POST', body: JSON.stringify(payload) }),
  updateTenantBrandAuthorization: (authorizationId: string, payload: Record<string, unknown>) => request(`/api/v1/admin/master-data/tenant-brand-authorizations/${authorizationId}`, { method: 'PUT', body: JSON.stringify(payload) }),
  createBrand: (payload: Record<string, unknown>) => request('/api/v1/admin/master-data/brands', { method: 'POST', body: JSON.stringify(payload) }),
  updateBrand: (brandId: string, payload: Record<string, unknown>) => request(`/api/v1/admin/master-data/brands/${brandId}`, { method: 'PUT', body: JSON.stringify(payload) }),
  getProjects: () => request<ProjectItem[]>('/api/v1/admin/master-data/projects'),
  createProject: (payload: Record<string, unknown>) => request('/api/v1/admin/master-data/projects', { method: 'POST', body: JSON.stringify(payload) }),
  updateProject: (projectId: string, payload: Record<string, unknown>) => request(`/api/v1/admin/master-data/projects/${projectId}`, { method: 'PUT', body: JSON.stringify(payload) }),
  getStores: () => request<StoreItem[]>('/api/v1/admin/master-data/stores'),
  createStore: (payload: Record<string, unknown>) => request('/api/v1/admin/master-data/stores', { method: 'POST', body: JSON.stringify(payload) }),
  updateStore: (storeId: string, payload: Record<string, unknown>) => request(`/api/v1/admin/master-data/stores/${storeId}`, { method: 'PUT', body: JSON.stringify(payload) }),
  getMasterProfiles: () => request<ProfileItem[]>('/api/v1/admin/master-data/profiles'),
  createProfile: (payload: Record<string, unknown>) => request('/api/v1/admin/master-data/profiles', { method: 'POST', body: JSON.stringify(payload) }),
  updateProfile: (profileId: string, payload: Record<string, unknown>) => request(`/api/v1/admin/master-data/profiles/${profileId}`, { method: 'PUT', body: JSON.stringify(payload) }),
  getMasterTemplates: () => request<TerminalTemplateItem[]>('/api/v1/admin/master-data/templates'),
  createTemplate: (payload: Record<string, unknown>) => request('/api/v1/admin/master-data/templates', { method: 'POST', body: JSON.stringify(payload) }),
  updateTemplate: (templateId: string, payload: Record<string, unknown>) => request(`/api/v1/admin/master-data/templates/${templateId}`, { method: 'PUT', body: JSON.stringify(payload) }),
  getTerminals: () => request<TerminalItem[]>('/api/v1/admin/terminals'),
  getActivationCodes: () => request<ActivationCodeItem[]>('/api/v1/admin/activation-codes'),
  getTaskReleases: () => request<TaskReleaseItem[]>('/api/v1/admin/tasks/releases'),
  getTaskInstances: () => request<TaskInstanceItem[]>('/api/v1/admin/tasks/instances'),
  getTaskTrace: (instanceId: string) => request<TaskTrace>(`/api/v1/admin/tasks/instances/${instanceId}/trace`),
  getSessions: () => request<SessionItem[]>('/api/v1/admin/tdp/sessions'),
  connectSession: (payload: Record<string, unknown>) => request('/api/v1/tdp/sessions/connect', { method: 'POST', body: JSON.stringify(payload) }),
  disconnectSession: (sessionId: string) => request(`/api/v1/tdp/sessions/${sessionId}/disconnect`, { method: 'POST' }),
  heartbeatSession: (sessionId: string) => request(`/api/v1/tdp/sessions/${sessionId}/heartbeat`, { method: 'POST' }),
  getTopics: () => request<TopicItem[]>('/api/v1/admin/tdp/topics'),
  getScopeStats: () => request<ScopeStats>('/api/v1/admin/tdp/scopes'),
  getProjections: () => request<ProjectionItem[]>('/api/v1/admin/tdp/projections'),
  getChangeLogs: () => request<ChangeLogItem[]>('/api/v1/admin/tdp/change-logs'),
  getTerminalSnapshot: (terminalId: string) => request(`/api/v1/tdp/terminals/${terminalId}/snapshot`),
  getTerminalChanges: (terminalId: string) => request(`/api/v1/tdp/terminals/${terminalId}/changes`),
  getSceneTemplates: () => request<SceneTemplateItem[]>('/mock-admin/scenes/templates'),
  getFaultRules: () => request<FaultRuleItem[]>('/mock-admin/fault-rules'),
  batchCreateTerminals: (count: number) => request<{ count: number; terminalIds: string[] }>('/mock-admin/terminals/batch-create', { method: 'POST', body: JSON.stringify({ count }) }),
  batchCreateActivationCodes: (payload: number | Record<string, unknown>) =>
    request<{ count: number; codes: string[] }>('/api/v1/admin/activation-codes/batch', {
      method: 'POST',
      body: JSON.stringify(typeof payload === 'number' ? { count: payload } : payload),
    }),
  activateTerminal: (payload: Record<string, unknown>) => request<ActivationResult>('/api/v1/terminals/activate', { method: 'POST', body: JSON.stringify(payload) }),
  forceTerminalStatus: (terminalId: string, payload: Record<string, unknown>) => request(`/mock-admin/terminals/${terminalId}/force-status`, { method: 'POST', body: JSON.stringify(payload) }),
  createTaskRelease: (payload: Record<string, unknown>) => request('/api/v1/admin/tasks/releases', { method: 'POST', body: JSON.stringify(payload) }),
  createTopic: (payload: Record<string, unknown>) => request('/api/v1/admin/tdp/topics', { method: 'POST', body: JSON.stringify(payload) }),
  upsertProjection: (payload: Record<string, unknown>) => request('/api/v1/admin/tdp/projections/upsert', { method: 'POST', body: JSON.stringify(payload) }),
  runSceneTemplate: (sceneTemplateId: string) => request(`/mock-admin/scenes/${sceneTemplateId}/run`, { method: 'POST' }),
  createFaultRule: (payload: Record<string, unknown>) => request('/mock-admin/fault-rules', { method: 'POST', body: JSON.stringify(payload) }),
  updateFaultRule: (faultRuleId: string, payload: Record<string, unknown>) => request(`/mock-admin/fault-rules/${faultRuleId}`, { method: 'PUT', body: JSON.stringify(payload) }),
  simulateFaultHit: (faultRuleId: string) => request(`/mock-admin/fault-rules/${faultRuleId}/hit`, { method: 'POST' }),
  mockTaskResult: (instanceId: string, payload: Record<string, unknown>) => request(`/mock-debug/tasks/${instanceId}/mock-result`, { method: 'POST', body: JSON.stringify(payload) }),
}
