export enum ExecutionType {
    SEND_AND_EXECUTE_SEPARATELY = 'SEND_AND_EXECUTE_SEPARATELY',
    SLAVE_SEND_MASTER_EXECUTE = 'SLAVE_SEND_MASTER_EXECUTE',
    ONLY_SEND_AND_EXECUTE_ON_MASTER = 'ONLY_SEND_AND_EXECUTE_ON_MASTER',
    ONLY_SEND_AND_EXECUTE_ON_SLAVE = 'ONLY_SEND_AND_EXECUTE_ON_SLAVE'
}

export interface ExecutePath {
    id: string,
    type: string
}

