export const TOPOLOGY_V2_RECOVERY_STATE_KEY = 'kernel.base.topology-runtime-v2.recovery'
export const TOPOLOGY_V2_CONTEXT_STATE_KEY = 'kernel.base.topology-runtime-v2.context'
export const TOPOLOGY_V2_CONNECTION_STATE_KEY = 'kernel.base.topology-runtime-v2.connection'
export const TOPOLOGY_V2_PEER_STATE_KEY = 'kernel.base.topology-runtime-v2.peer'
export const TOPOLOGY_V2_SYNC_STATE_KEY = 'kernel.base.topology-runtime-v2.sync'
