import {moduleName} from '../../moduleName'

export const tdpSyncCommandNames = {
    bootstrapTdpSync: `${moduleName}.bootstrap-tdp-sync`,
    bootstrapTdpSyncSucceeded: `${moduleName}.bootstrap-tdp-sync-succeeded`,
    connectTdpSession: `${moduleName}.connect-tdp-session`,
    disconnectTdpSession: `${moduleName}.disconnect-tdp-session`,
    acknowledgeCursor: `${moduleName}.acknowledge-cursor`,
    reportAppliedCursor: `${moduleName}.report-applied-cursor`,
    sendPing: `${moduleName}.send-ping`,
    tdpSocketConnected: `${moduleName}.tdp-socket-connected`,
    tdpSocketReconnecting: `${moduleName}.tdp-socket-reconnecting`,
    tdpSocketDisconnected: `${moduleName}.tdp-socket-disconnected`,
    tdpSocketErrored: `${moduleName}.tdp-socket-errored`,
    tdpSocketHeartbeatTimedOut: `${moduleName}.tdp-socket-heartbeat-timed-out`,
    tdpMessageReceived: `${moduleName}.tdp-message-received`,
    tdpSessionReady: `${moduleName}.tdp-session-ready`,
    tdpSnapshotLoaded: `${moduleName}.tdp-snapshot-loaded`,
    tdpChangesLoaded: `${moduleName}.tdp-changes-loaded`,
    tdpProjectionReceived: `${moduleName}.tdp-projection-received`,
    tdpProjectionBatchReceived: `${moduleName}.tdp-projection-batch-received`,
    tdpCommandDelivered: `${moduleName}.tdp-command-delivered`,
    tdpPongReceived: `${moduleName}.tdp-pong-received`,
    tdpEdgeDegraded: `${moduleName}.tdp-edge-degraded`,
    tdpSessionRehomeRequired: `${moduleName}.tdp-session-rehome-required`,
    tdpProtocolFailed: `${moduleName}.tdp-protocol-failed`,
} as const
