export type AutomationTarget = 'primary' | 'secondary' | 'host' | 'all'

export type AutomationMethod =
    | 'session.hello'
    | 'runtime.getInfo'
    | 'runtime.getState'
    | 'runtime.selectState'
    | 'runtime.listRequests'
    | 'runtime.getRequest'
    | 'runtime.getCurrentScreen'
    | 'ui.getTree'
    | 'ui.queryNodes'
    | 'ui.getNode'
    | 'ui.getFocusedNode'
    | 'ui.getBounds'
    | 'ui.performAction'
    | 'ui.revealNode'
    | 'ui.scroll'
    | 'ui.setValue'
    | 'ui.clearValue'
    | 'ui.submit'
    | 'wait.forNode'
    | 'wait.forScreen'
    | 'wait.forState'
    | 'wait.forRequest'
    | 'wait.forIdle'
    | 'events.subscribe'
    | 'events.unsubscribe'
    | 'automation.getLastTrace'
    | 'automation.getTraceHistory'
    | 'automation.clearTrace'
    | 'command.dispatch'
    | 'scripts.execute'
