import type {
  ContractLifecycleDraft,
  DomainDefinition,
  EnvironmentDraft,
  IamDraft,
  MenuDraft,
  OperationDraft,
  OrganizationDraft,
  ProductDraft,
} from './types'

export const DOMAINS: DomainDefinition[] = [
  {
    key: 'environment',
    label: '初始化与环境',
    eyebrow: 'UC-01 Seed And Sandbox',
    title: '系统初始化向导与环境准备',
    description: '收拢初始化、seed、legacy 文档兼容与 auth 边界预留，作为整套本地 mock 后台的运行入口。',
  },
  {
    key: 'organization',
    label: '组织与租户',
    eyebrow: 'UC-01 Organization',
    title: '组织驾驶舱与租户主链路',
    description: '围绕平台、项目、租户、品牌、门店、合同与法人主体，建立 contract-driven 的组织真相源与组织树视图。',
  },
  {
    key: 'facilities',
    label: '门店设施',
    eyebrow: 'UC-01 Facilities',
    title: '桌台与工作站设施管理',
    description: '把桌台与工作站从组织主链路中抽出为独立工作区，便于后续对接 KDS、生产分工和二维码流程。',
  },
  {
    key: 'iam',
    label: '用户与权限',
    eyebrow: 'UC-02 IAM',
    title: '店铺级 IAM 与权限测试',
    description: '展示用户、权限目录、角色与绑定的 store-effective 关系，并显式保留未来登录协议边界。',
  },
  {
    key: 'products',
    label: '餐饮商品',
    eyebrow: 'UC-03 Product',
    title: '餐饮商品与生产画像',
    description: '承接品牌/门店商品、规格、加料、套餐与生产画像等餐饮语义，不再停留在简化商品卡片视图。',
  },
  {
    key: 'menus',
    label: '品牌菜单',
    eyebrow: 'UC-03 Menu',
    title: '品牌菜单审核与门店菜单发布',
    description: '同时看到 brand source 与 store-effective menu，作为品牌菜单审核、发布、版本回滚的产品化壳层。',
  },
  {
    key: 'operations',
    label: '门店经营',
    eyebrow: 'UC-03 Operation',
    title: '门店经营状态与运行规则',
    description: '围绕营业状态、可售性、价格规则、库存和经营配置建立独立的运营工作区。',
  },
  {
    key: 'projection',
    label: '投影与联调',
    eyebrow: 'TDP Diagnostics',
    title: '业务事件、Outbox 与终端联调',
    description: '沿着 aggregate -> event -> outbox -> TDP -> terminal receipt 的链路做发布、回放、诊断与观测。',
  },
]

export const defaultOrganizationDraft: OrganizationDraft = {
  tenantCode: 'TENANT_LIVE_NOVA',
  tenantName: 'Live Nova Tenant',
  brandCode: 'BRAND_LIVE_BISTRO',
  brandName: 'Live Bistro',
  entityCode: 'ENTITY_LIVE_BISTRO',
  entityName: 'Live Bistro Commercial Co.',
  storeCode: 'STORE_LIVE_BISTRO_SZ',
  storeName: 'Live Bistro Shenzhen',
  unitCode: 'SZ-018',
  contractNo: 'CTR-2026-LIVE-BISTRO',
  startDate: '2026-05-01',
  endDate: '2027-04-30',
  commissionType: 'FIXED_RATE',
  commissionRate: '8.5',
  depositAmount: '5000000',
}

export const defaultContractLifecycleDraft: ContractLifecycleDraft = {
  newEndDate: '2028-04-30',
  amendedEndDate: '2027-12-31',
  amendedCommissionRate: '9.2',
}

export const defaultEnvironmentDraft: EnvironmentDraft = {
  sandboxCode: 'SANDBOX_LIVE_DEBUG',
  sandboxName: 'Live Debug Sandbox',
  sandboxType: 'DEBUG',
  sandboxOwner: 'Dexter',
  sandboxDescription: 'Workflow-first admin mall tenant console verification sandbox.',
  platformCode: 'PLATFORM_LIVE_NOVA',
  platformName: 'Live Nova Commercial Platform',
  platformDescription: 'Aligned organization-service mock platform for local mall operations.',
  platformContactName: 'Mall Platform Ops',
  platformContactPhone: '400-810-8090',
  projectCode: 'PROJECT_LIVE_NOVA_SZ',
  projectName: 'Live Nova Shenzhen Bay',
  projectTimezone: 'Asia/Shanghai',
  projectAddress: 'Shenzhen Nanshan District Shenzhen Bay MixC',
  projectBusinessMode: 'SHOPPING_MALL',
  projectRegionCode: 'CN-SZ',
  projectRegionName: 'Shenzhen',
  projectParentRegionCode: 'CN-GD',
  projectRegionLevel: '2',
  isvProviderType: 'LOCAL_MOCK_ISV',
  isvAppKey: 'live_nova_app_key_2026',
  isvAppSecret: 'live_nova_app_secret_2026',
  isvToken: 'live_nova_token_2026_04_24',
  isvTokenExpireAt: '2026-06-30T23:59:59.000Z',
  isvChannelStatus: 'ACTIVE',
}

export const defaultIamDraft: IamDraft = {
  storeId: 'store-kernel-base-test',
  userCode: 'zhao.min',
  displayName: 'Zhao Min',
  mobile: '13800000009',
  roleCode: 'SHIFT_LEAD',
  roleName: 'Shift Lead',
  scopeType: 'ORG_NODE',
  permissionId: 'perm-product-manage',
  permissionCode: 'PRODUCT_MANAGE',
}

export const defaultProductDraft: ProductDraft = {
  productName: 'Citrus Shrimp Bowl',
  ownershipScope: 'BRAND',
  brandId: 'brand-kernel-base-test',
  storeId: 'store-kernel-base-test',
  productType: 'STANDARD',
  basePrice: '68',
  productionStepName: 'Finish Bowl',
  workstationCode: 'HOT_KITCHEN',
  modifierGroupName: 'Spice Level',
  variantName: 'Large Portion',
  comboGroupName: 'Drink Pairing',
}

export const defaultMenuDraft: MenuDraft = {
  brandId: 'brand-kernel-base-test',
  storeId: 'store-kernel-base-test',
  menuName: 'Citrus Shrimp Seasonal Menu',
  sectionName: 'Seasonal Specials',
  storeMenuName: 'Citrus Shrimp Shenzhen Effective Menu',
}

export const defaultOperationDraft: OperationDraft = {
  storeId: 'store-kernel-base-test',
  productId: 'product-salmon-bowl',
  businessStatus: 'OPEN',
  acceptOrder: true,
  weekday: '5',
  startTime: '10:00',
  endTime: '22:30',
  extraChargeName: 'Late Night Packing Fee',
  extraChargeAmount: '3',
  stockId: 'stock-product-salmon-bowl',
  saleableQuantity: '18',
  safetyStock: '5',
  soldOutReason: 'MANUAL_STAFF_PAUSE',
  priceRuleCode: 'PRICE_LATE_NIGHT',
  priceDelta: '4',
  priceType: 'STANDARD',
  channelType: 'POS',
  availabilityRuleCode: 'AVAILABILITY_LATE_NIGHT',
  availabilityChannelType: 'TAKEAWAY',
  availabilityAllowed: false,
  reservationId: 'reservation-salmon-bowl-shift-b',
  reservedQuantity: '3',
  reservationStatus: 'ACTIVE',
  reservationExpiresAt: '2026-04-24T23:30:00.000Z',
}
